[2025-03-24T09:35:37.590+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T09:35:37.613+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_eng_dag_etl.process_snowflake_file manual__2025-03-24T09:35:34.284921+00:00 [queued]>
[2025-03-24T09:35:37.621+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_eng_dag_etl.process_snowflake_file manual__2025-03-24T09:35:34.284921+00:00 [queued]>
[2025-03-24T09:35:37.622+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T09:35:37.632+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_snowflake_file> on 2025-03-24 09:35:34.284921+00:00
[2025-03-24T09:35:37.637+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T09:35:37.637+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2025-03-24T09:35:37.638+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_eng_dag_etl', 'process_snowflake_file', 'manual__2025-03-24T09:35:34.284921+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/data-eng-dag-etl/dag.py', '--cfg-path', '/tmp/tmpyaci1sh7']
[2025-03-24T09:35:37.640+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask process_snowflake_file
[2025-03-24T09:35:37.701+0000] {task_command.py:467} INFO - Running <TaskInstance: data_eng_dag_etl.process_snowflake_file manual__2025-03-24T09:35:34.284921+00:00 [running]> on host ecaa4734a2ff
[2025-03-24T09:35:37.802+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_eng_dag_etl' AIRFLOW_CTX_TASK_ID='process_snowflake_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T09:35:34.284921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T09:35:34.284921+00:00'
[2025-03-24T09:35:37.804+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T09:35:37.837+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-03-24T09:35:37.838+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.36
[2025-03-24T09:35:37.840+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-24T09:35:37.840+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-24T09:35:40.883+0000] {sql.py:511} INFO - Running statement: LIST @RECRUITMENT_DB.PUBLIC.S3_FOLDER;, parameters: None
[2025-03-24T09:35:41.795+0000] {sql.py:520} INFO - Rows affected: 1
[2025-03-24T09:35:41.796+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:468: DeprecationWarning: Import of fetch_one_handler from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  result = self._make_common_data_structure(handler(cur))  # type: ignore[attr-defined]

[2025-03-24T09:35:41.799+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:469: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(sql, return_last, split_statements):

[2025-03-24T09:35:41.800+0000] {snowflake.py:477} INFO - Rows affected: 1
[2025-03-24T09:35:41.800+0000] {snowflake.py:478} INFO - Snowflake query id: 01bb381f-0907-c6ea-006a-f2030076987e
[2025-03-24T09:35:42.079+0000] {connection.py:803} INFO - closed
[2025-03-24T09:35:42.326+0000] {connection.py:809} INFO - No async queries seem to be running, deleting session
[2025-03-24T09:35:42.590+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:487: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(sql, return_last, split_statements):

[2025-03-24T09:35:42.591+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: ('s3://iw-recruiting-dataset/flights.gz', 48835247, '5e3e1b99afa2998e7459bab2cdc2ee90-3', 'Wed, 6 Jul 2022 01:43:24 GMT')
[2025-03-24T09:35:42.592+0000] {logging_mixin.py:190} INFO - Arquivo encontrado: s
[2025-03-24T09:35:42.592+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-eng-dag-etl/dag.py", line 44, in process_snowflake_file
    hook.download_file(s3_path, local_path)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'SnowflakeHook' object has no attribute 'download_file'
[2025-03-24T09:35:42.611+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=data_eng_dag_etl, task_id=process_snowflake_file, run_id=manual__2025-03-24T09:35:34.284921+00:00, execution_date=20250324T093534, start_date=20250324T093537, end_date=20250324T093542
[2025-03-24T09:35:42.658+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T09:35:42.659+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task process_snowflake_file ('SnowflakeHook' object has no attribute 'download_file'; 103)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-eng-dag-etl/dag.py", line 44, in process_snowflake_file
    hook.download_file(s3_path, local_path)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'SnowflakeHook' object has no attribute 'download_file'
[2025-03-24T09:35:42.677+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T09:35:42.711+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T09:35:42.717+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
